server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "8090"
echoiot:
  enableProxy: "false"
  # Echoiot node host
  host: "localhost"
  # Echoiot node port
  port: "8080"
logger:
  level: "info"
  path: "logs"
  filename: "tb-web-ui-%DATE%.log"
