version: '3.0'

services:
  postgres:
    restart: always
    image: "postgres:12"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: echoiot
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tb-node/postgres:/var/lib/postgresql/data
  cassandra:
    restart: always
    image: "cassandra:4.0.4"
    ports:
      - "9042"
    volumes:
      - ./tb-node/cassandra:/var/lib/cassandra
  tb-core1:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra
  tb-core2:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra
  tb-rule-engine1:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra
  tb-rule-engine2:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra
