version: '3.0'

services:
# Redis standalone
  redis:
    restart: always
    image: bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '6379:6379'
    volumes:
      - ./tb-node/redis-data:/bitnami/redis/data

# Echoiot setup to use redis-standalone
  tb-core1:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-core2:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-rule-engine1:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-rule-engine2:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-mqtt-transport1:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-mqtt-transport2:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-http-transport1:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-http-transport2:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-coap-transport:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-lwm2m-transport:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-snmp-transport:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-vc-executor1:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-vc-executor2:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
