version: '3.0'

services:
  kafka:
    restart: always
    image: "bitnami/kafka:3.2.0"
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    depends_on:
      - zookeeper
  tb-js-executor:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-core1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-core2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-rule-engine1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-rule-engine2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-mqtt-transport1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-mqtt-transport2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-http-transport1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-http-transport2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-coap-transport:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-lwm2m-transport:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-snmp-transport:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-vc-executor1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-vc-executor2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
