version: '3.0'

services:
  postgres:
    restart: always
    image: "postgres:12"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: echoiot
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tb-node/postgres:/var/lib/postgresql/data
  tb-core1:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
  tb-core2:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
  tb-rule-engine1:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
  tb-rule-engine2:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
