version: '3.0'

services:
  tb-core1:
    volumes:
      - tb-log-volume:/var/log/echoiot
  tb-core2:
    volumes:
      - tb-log-volume:/var/log/echoiot
  tb-rule-engine1:
    volumes:
      - tb-log-volume:/var/log/echoiot
  tb-rule-engine2:
    volumes:
      - tb-log-volume:/var/log/echoiot
  tb-coap-transport:
    volumes:
      - tb-coap-transport-log-volume:/var/log/tb-coap-transport
  tb-lwm2m-transport:
    volumes:
      - tb-lwm2m-transport-log-volume:/var/log/tb-lwm2m-transport
  tb-http-transport1:
    volumes:
      - tb-http-transport-log-volume:/var/log/tb-http-transport
  tb-http-transport2:
    volumes:
      - tb-http-transport-log-volume:/var/log/tb-http-transport
  tb-mqtt-transport1:
    volumes:
      - tb-mqtt-transport-log-volume:/var/log/tb-mqtt-transport
  tb-mqtt-transport2:
    volumes:
      - tb-mqtt-transport-log-volume:/var/log/tb-mqtt-transport
  tb-snmp-transport:
    volumes:
      - tb-snmp-transport-log-volume:/var/log/tb-snmp-transport
  tb-vc-executor1:
    volumes:
      - tb-vc-executor-log-volume:/var/log/tb-vc-executor
  tb-vc-executor2:
    volumes:
      - tb-vc-executor-log-volume:/var/log/tb-vc-executor

volumes:
  tb-log-volume:
    external:
      name: ${TB_LOG_VOLUME}
  tb-coap-transport-log-volume:
    external:
      name: ${TB_COAP_TRANSPORT_LOG_VOLUME}
  tb-lwm2m-transport-log-volume:
    external:
      name: ${TB_LWM2M_TRANSPORT_LOG_VOLUME}
  tb-http-transport-log-volume:
    external:
      name: ${TB_HTTP_TRANSPORT_LOG_VOLUME}
  tb-mqtt-transport-log-volume:
    external:
      name: ${TB_MQTT_TRANSPORT_LOG_VOLUME}
  tb-snmp-transport-log-volume:
    external:
      name: ${TB_SNMP_TRANSPORT_LOG_VOLUME}
  tb-vc-executor-log-volume:
    external:
      name: ${TB_VC_EXECUTOR_LOG_VOLUME}
